[package]
name = "memory-adaptor"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.89"
chrono = "0.4.43"
common = { path = "../../common" }
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
